config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :books, only: [:new, :create] do
    resources :loans, only: [:new, :create, :update]
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :loans, dependent: :destroy

  validates :title, :author, presence: true

  def loaned?
    self.loans.where(status: "loaned").count > 0
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :user
  belongs_to :book

  validates :user_id, :book_id, :status, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books, dependent: :destroy
  has_many :loans, through: :books
  has_many :borrowings, class_name: "Loan", dependent: :destroy

  validates :username, uniqueness: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    authorize @book
    if @book.save
      flash[:notice] = "Successfully added #{@book.title} to your collection"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    authorize @book
  end

  def update
    authorize @book
    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize @book
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :find_book, only: [:new, :create]

  def new
    @users = User.where.not(id: current_user.id).order(username: :asc)
    @loan = Loan.new
    authorize @loan
  end

  def create
    @loan = Loan.new
    @loan.book = @book
    @loan.user = User.find_by_id(loan_params[:user_id])
    @loan.status = "loaned"
    authorize @loan
    if @loan.save
      flash[:notice] = "#{@loan.book.title} loaned to #{@loan.user.username}"
      redirect_to :root
    else
      @users = User.where.not(id: current_user.id).order(username: :asc)
      render :new
    end
  end

  def update
    @loan = Loan.find(params[:id])
    authorize @loan
    if @loan.update(status: "returned")
      flash[:notice] = "#{@loan.book.title} returned to #{@loan.book.user.username}"
      redirect_to :root
    else
      flash[:error] = "Impossible to return book"
      redirect_to :root
    end
  end

  private

  def loan_params
    params.require(:loan).permit(:user_id)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized, only: :home
  skip_after_action :verify_policy_scoped , only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.submit "Add Book", class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <h1>Add a new Book</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBookstore</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/loans/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Loan "<%= @book.title %>"</h1>
      <%= simple_form_for([@book, @loan]) do |f| %>
        <%= f.input :user_id, collection: @users.map { |user| [user.username, user.id] }, prompt: "Select a User" %>
        <%= f.submit "Loan book", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <div class="text-center home-wrapper">
        <h1>Welcome to the Bookstore!</h1>
        <p>Sign up to access to all the functionalities</p>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <a href="#" id="navbar-wagon-menu" data-toggle="dropdown"><i class="fa fa-user"></i></a>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to "Add a New Book", new_book_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</div>

app/views/users/_borrowed_book.html.erb
<div class="book-card">
  <h4><%= borrowing.book.title %></h4>
  <p>Borrowed from <%= borrowing.book.user.username %> - <%= link_to "Return Book", book_loan_path(borrowing.book, borrowing), method: :put %></p>
</div>

app/views/users/_loaned_book.html.erb
<div class="book-card">
  <h4><%= loan.book.title %></h4>
  <p>Loaned to <%= loan.user.username %></p>
</div>

app/views/users/_user_book.html.erb
<div class="book-card">
  <h4><%= book.title %></h4>
  <p>
    <%= book.author %>
    <% if book.loaned? %>
      <span class="label label-success">loaned</span>
    <% else %>
      <%= link_to "Loan Book", new_book_loan_path(book) %>
    <% end %>
  </p>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <div class="profile-info">
        <h1>Profile</h1>
        <p><%= @user.username %></p>
      </div>
    </div>

    <div class="col-xs-12 col-sm-9">
      <div class="books-list">
        <h3>My Books</h3>
        <% @user.books.each do |book| %>
          <%= render "user_book", book: book %>
        <% end %>
      </div>

      <div class="row">
        <div class="col-xs-6">
          <div class="books-list">
            <h3>Borrowed Books</h3>
            <% @user.borrowings.where(status: "loaned").each do |borrowing| %>
              <%= render "borrowed_book", borrowing: borrowing %>
            <% end %>
          </div>
        </div>

        <div class="col-xs-6">
          <div class="books-list">
            <h3>Loaned Books</h3>
            <% @user.loans.where(status: "loaned").each do |loan| %>
              <%= render "loaned_book", loan: loan %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>